DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS participation_requests CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS compilation_events CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS event_statistics CASCADE;
DROP TABLE IF EXISTS request_events CASCADE;

CREATE TABLE users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(250) NOT NULL,
    email   VARCHAR(254) NOT NULL UNIQUE,
    created TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    status  VARCHAR(20) DEFAULT 'ACTIVE',
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    created     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(2000) NOT NULL,
    description        VARCHAR(7000),
    title              VARCHAR(120)  NOT NULL,
    event_date         TIMESTAMP     NOT NULL,
    created_on         TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    published_on       TIMESTAMP,
    paid               BOOLEAN     DEFAULT FALSE,
    participant_limit  INTEGER     DEFAULT 0,
    request_moderation BOOLEAN     DEFAULT TRUE,
    state              VARCHAR(20) DEFAULT 'PENDING',
    views              TEXT[]      DEFAULT '{}',

    initiator_id       BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category_id        BIGINT        NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,
    location_id        BIGINT        NOT NULL REFERENCES locations (id) ON DELETE RESTRICT,

    CONSTRAINT chk_event_state CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED'))
);

CREATE TABLE requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    status       VARCHAR(20) DEFAULT 'PENDING',

    requester_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    event_id     BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,

    CONSTRAINT uq_request_user_event UNIQUE (requester_id, event_id),
    CONSTRAINT chk_request_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE compilations
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(50) NOT NULL UNIQUE,
    pinned      BOOLEAN   DEFAULT FALSE,
    description VARCHAR(500),
    created     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_compilation_title UNIQUE (title)
);

CREATE TABLE compilation_events
(
    compilation_id BIGINT NOT NULL REFERENCES compilations (id) ON DELETE CASCADE,
    event_id       BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    added_date     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE request_events
(
    request_id BIGINT NOT NULL REFERENCES requests (id) ON DELETE CASCADE,
    event_id   BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    added_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (request_id, event_id)
);

CREATE TABLE comments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text              VARCHAR(2000) NOT NULL,
    created           TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    author_id         BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    event_id          BIGINT        NOT NULL REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(200),
    CONSTRAINT uq_role_name UNIQUE (name)
);

CREATE TABLE user_roles
(
    user_id       BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id       BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    assigned_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);

INSERT INTO roles (name, description)
VALUES ('USER', 'Обычный пользователь'),
       ('ADMIN', 'Администратор системы'),
       ('MODERATOR', 'Модератор контента');

INSERT INTO categories (name, description)
VALUES ('Концерты', 'Музыкальные мероприятия и выступления'),
       ('Выставки', 'Художественные и культурные выставки'),
       ('Спорт', 'Спортивные мероприятия и соревнования'),
       ('Образование', 'Образовательные мероприятия и лекции'),
       ('Развлечения', 'Развлекательные мероприятия и шоу');